docker/docker-compose.yml
Issues: #5
#5 
- Docker-compose를 통한 postgreSQL, Redis 세팅
>
=> Feat : Docker-compose를 통한 postgreSQL, Redis 세팅

com.sparta.logistics.client.hub/build.gradle, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/common/Timestamped.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/enums/CompanyType.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/model/Company.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/model/Hub.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/model/HubPath.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/model/Product.java
#10 
- Hub Service 엔티티 추가 (Hub, Hub Path, Product, Company)
- 일단 저도 Common 만들고, Timestamped 만들었는데 추후에 공통클래스로 뺀다면 삭제하겠습니다.
=> Feat : Hub Service 엔티티 추가

com.sparta.logistics.client.order/build.gradle, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/common/Timestamped.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/common/type/DeliveryStatus.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/common/type/OrderStatus.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/domain/model/Delivery.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/domain/model/DeliveryPaths.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/domain/model/OrderProducts.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/domain/model/Orders.java, com.sparta.logistics.client.order/src/main/resources/application.yml
Issues : #9
> #9
>  Order Service Entity 작업
>
=> Feat : Order Service Entity 작업

build.gradle, com.sparta.logistics.client.ai/build.gradle, com.sparta.logistics.client.ai/settings.gradle, com.sparta.logistics.client.auth/build.gradle, com.sparta.logistics.client.auth/settings.gradle, com.sparta.logistics.client.gateway/build.gradle, com.sparta.logistics.client.gateway/settings.gradle, com.sparta.logistics.client.hub/build.gradle, com.sparta.logistics.client.hub/settings.gradle, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/model/Hub.java, com.sparta.logistics.client.order/build.gradle, com.sparta.logistics.client.order/settings.gradle, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/domain/model/Orders.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/presentation/controller/OrderController.java, com.sparta.logistics.client.user/build.gradle, com.sparta.logistics.client.user/settings.gradle, com.sparta.logistics.eureka.server/build.gradle, com.sparta.logistics.eureka.server/settings.gradle, settings.gradle
Issues : #14
> #14 
>
- 멀티모듈 구성 
- common 모듈 추가
- 각 서비스에서 settings.gradle 삭제
- 각 서비스 dependency에 common 추가
- 
>
=> Feat : 멀티모듈 구성 & common모듈 생성

com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/controller/HubController.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/dto/HubRequestDto.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/dto/HubResponseDto.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/model/Hub.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/repository/HubRepository.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/service/HubService.java, com.sparta.logistics.client.hub/src/main/resources/application.yml
Issues: #13
#13 
- Hub CRUD 구현
- Eureka Client연결 X, Hub CRUD 초안입니다.
>
=> Feat : Hub CRUD 기능 구현

com.sparta.logistics.client.hub/build.gradle, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/config/CacheConfig.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/controller/HubController.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/service/HubService.java, com.sparta.logistics.client.hub/src/main/resources/application.yml
Issues: #22
#22 
- 허브 조회 시 캐시 생성 (@Cacheable 사용)
- 허브 수정 시 해당 허브 캐시 수정 (@CachePut 사용)
- 새로운 허브 생성 시 전체 허브 조회 캐시 삭제 (@CacheEvict 사용)
>
https://backtony.tistory.com/32
=> Feat : Hub 허브 정보 캐싱

com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/controller/HubController.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/dto/HubResponseDto.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/model/Hub.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/repository/HubRepository.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/service/HubService.java
Issues: #24
#24 
모든 조회 및 검색에서 is_delete가 false인 데이터만을 대상으로 처리
>
=> Feat : Hub 허브 is_delete가 false인 데이터만을 대상으로 처리하도록 수정

com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/common/exception/HubException.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/controller/CompanyController.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/dto/CompanyRequestDto.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/dto/CompanyResponseDto.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/model/Company.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/repository/CompanyRepository.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/service/CompanyService.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/service/HubService.java, com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/type/ApiResultError.java
Issues: #31
#31 
- Company 업체 CRUD 기능 구현
- Search 및 다른 권한관리 추가예정
>
=> Feat : Company 업체 CRUD 기능구현

build.gradle, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/controller/OrderController.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/dto/OrderRequestDto.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/model/validation/OrderValid0001.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/model/validation/OrderValid0002.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/service/OrderProcService.java, com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/controller/CustomApiController.java
Issues : 29
> #29
> Order에 validation 추가하여 Request Body biding error 처리하는 예제 추가했습니다.
공통 모듈에 있는 CustomApiController를 extends하여 사용하시면 됩니다. 
루트 모듈 dependency에 validation 추가했으니 따로 추가하셨으면 서브 모듈에서는 삭제하셔도 됩니다.
>
=> FEAT : Order Validation 추가

com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/common/exception/OrderProcException.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/controller/OrderController.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/dto/OrderProductRequestDto.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/dto/OrderProductResponseDto.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/dto/OrderRequestDto.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/dto/OrderResponseDto.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/model/OrderProduct.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/repository/OrderProductRepository.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/service/OrderProcService.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/service/OrderProductService.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/service/OrderService.java, com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/type/ApiResultError.java
Issues : 35
> #35 
> Order Product CRUD 구현
>
=> FEAT : Order Product CRUD 구현

com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/common/BaseEntity.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/controller/DeliveryManagerController.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/controller/UserController.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/dto/DeliveryManagerResponse.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/dto/ManagerRequestDto.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/dto/UserRequest.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/enums/DeliveryManagerType.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/enums/RoleType.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/model/DeliveryManager.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/model/User.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/model/UserVO.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/repository/DeliveryManagerRepository.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/repository/UserRepository.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/service/DeliveryManagerService.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/service/UserService.java
issues: #37
> delivery managers crud
> Delivery Manager Crud 작성했습니다. (hub 부분은 내일 합치면서 추가 할 예정이고)
>Create와 delete 부분은 구현만 해놓고 로그인 정보에서 받아와야 해서 controller부분만 주석처리 해놨습니다.
=> Feat/delivery managers crud #37

com.sparta.logistics.client.hub/build.gradle, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/config/QueryDSLConfig.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/controller/CompanyController.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/model/Hub.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/repository/CompanyRepository.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/repository/CompanyRepositoryCustom.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/repository/CompanyRepositoryImpl.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/service/CompanyService.java, com.sparta.logistics.common/build.gradle, com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/type/ApiResultError.java
Issues: #39
#39 
- Company 업체 Search 기능 구현
- Query DSL을 사용한 Search
>
https://velog.io/@kimsundae/Gradle-SpringBoot-3.x-QueryDSL-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0
=> Feat : Company Search 기능 구현

com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/controller/CompanyController.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/controller/HubController.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/dto/CompanyRequestDto.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/dto/HubRequestDto.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/model/validation/CompanyVaild0001.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/model/validation/HubValid0001.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/model/validation/HubValid0002.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/repository/HubRepository.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/repository/HubRepositoryCustom.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/repository/HubRepositoryImpl.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/service/CompanyService.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/service/HubService.java, com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/type/ApiResultError.java
#41 
- Hub 허브 검색 기능 구현(Query DSL)
- Hub 허브 RequestBody 바인딩 에러 처리
- Company 업체 RequestBody 바인딩 에러 처리
>
=> [FEAT] Hub 허브 검색 기능 구현 및 바인딩 에러처리

com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/controller/OrderController.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/dto/DeliveryRequestDto.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/dto/DeliveryResponseDto.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/dto/OrderProductRequestDto.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/dto/OrderRequestDto.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/dto/OrderResponseDto.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/model/Delivery.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/model/Order.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/repository/DeliveryRepository.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/service/DeliveryService.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/service/OrderProcService.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/service/OrderService.java, com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/model/ApiResult.java, com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/type/ApiResultError.java
Issues : 46
> #46
> Delivery CRUD 구현과 주문 생성 시 배송정보 자동생성 
>
=> FEAT : Delivery CRUD 구현

com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/dto/DeliveryPathRequestDto.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/dto/DeliveryPathResponseDto.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/model/DeliveryPath.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/repository/DeliveryPathRepository.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/service/DeliveryPathService.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/service/OrderProcService.java, com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/type/ApiResultError.java
Issues : 49
> #49 
> DeliveryPath CRUD 구현
>
=> FEAT : Delivery Path CRUD 구현

com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/controller/MessageController.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/dto/MessageRequestDto.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/dto/MessageResponse.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/dto/SearchRequest.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/model/Message.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/repository/MessageRepository.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/repository/UserRepository.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/service/MessageService.java, docker/docker-compose.yml
issues: #51 
[FEAT] Message Create, Search, Delete
=> [FEAT] Message Create, Search, Delete

com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/controller/ProductController.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/repository/ProductRepository.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/repository/ProductRepositoryCustom.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/repository/ProductRepositoryImpl.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/service/ProductService.java
Issues: #45
#45 
- Product 상품 Serach 기능 구현
>
=> Feat : Product 상품 Search 기능 구현

.gitignore, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/model/Delivery.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/model/DeliveryPath.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/repository/DeliveryPathRepository.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/service/DeliveryPathService.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/service/OrderProcService.java
Issues : 53
> #53
> Delivery Path 오류 수정
>
=> BUG : Delivery Path 오류 수정

com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/common/exception/UserException.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/controller/DeliveryManagerController.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/controller/MessageController.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/controller/UserController.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/dto/DeliveryManagerResponse.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/dto/ManagerRequestDto.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/dto/MessageRequestDto.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/dto/SearchRequest.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/dto/UserRequest.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/model/DeliveryManager.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/model/User.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/model/validation/DeliveryManagerValid0001.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/model/validation/DeliveryManagerValid0002.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/model/validation/MessageValid0001.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/model/validation/MessageValid0002.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/model/validation/UserValid0001.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/repository/UserRepository.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/service/DeliveryManagerService.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/service/MessageService.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/service/UserService.java, com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/type/ApiResultError.java
issues : #55 
공통 ApiResponse로 controller 수정
BaseEntity -> TimeStamped로 수정
=> [FEAT] Common structure #55 

com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/controller/HubPathController.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/dto/HubPathRequestDto.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/dto/HubPathResponseDto.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/dto/HubRequestDto.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/model/Hub.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/model/HubPath.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/model/validation/HubPathValid0001.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/repository/HubPathRepository.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/repository/HubPathRepositoryCustom.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/repository/HubPathRepositoryImpl.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/repository/HubRepository.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/service/HubPathService.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/service/HubService.java, com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/type/ApiResultError.java
Issues: #57
#57 
- HubPath 허브 이동 경로 CRUD
- 배송 이동 경로 애플리케이션에서 사용해야할 API 구현 (/hub-paths/hubList) departureHubId, arrivalHubId
>
=> Feat : HubPath 허브 이동 경로 CRUD 기능 구현

build.gradle, com.sparta.logistics.client.gateway/build.gradle, com.sparta.logistics.client.gateway/src/main/java/com/sparta/logistics/client/gateway/infrastructure/filter/LocalJwtAuthenticationFilter.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/controller/UserController.java, com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/CommonApplication.java
=> [FEAT] Swagger #60

com.sparta.logistics.client.hub/build.gradle, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/controller/HubPathController.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/dto/HubPathRequestDto.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/repository/HubPathRepository.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/repository/HubPathRepositoryCustom.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/repository/HubPathRepositoryImpl.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/service/HubPathService.java
#59 
- HubPath 허브 이동경로 검색 기능 + 페이징 기능 구현
- QueryDSL 사용
- 중복 되는 허브 이동 경로 전체 검색 API 삭제
>
=> [FEAT] HubPath 허브 이동 경로 검색 기능 구현

com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/controller/HubPathController.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/repository/HubPathRepository.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/repository/HubPathRepositoryCustom.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/repository/HubPathRepositoryImpl.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/service/HubPathService.java
Issues: #63
#63 
- HubPath 허브 이동경로 캐싱 적용
- 허브 이동경로 전체조회 추가
- 허브 이동경로 생성시 전체 조회 캐시 삭제
- 허브 이동경로 수정시 해당 캐시 수정 및 전체 조회 캐시 삭제
>
=> [FEAT] HubPath 캐싱 적용

com.sparta.logistics.client.hub/build.gradle, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/controller/CompanyController.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/controller/HubController.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/controller/HubPathController.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/controller/ProductController.java
#65 
- Hub, HubPath, Product, Company Swagger 적용
>
=> [FEAT] Hub, HubPath, Product, Company Swagger 적용

com.sparta.logistics.client.hub/src/main/resources/application.yml, com.sparta.logistics.common/build.gradle
#67 
- Common 모듈 의존성 추가
- Hub 애플리케이션 yml 설정 추가
>
=> [FEAT] Common 모듈 Zipkin 의존성 추가

com.sparta.logistics.client.hub/src/main/resources/application.yml, com.sparta.logistics.common/build.gradle, config/prometheus.yml
#69 
- Common 모듈 의존성 추가
- Hub Application yml 추가
- 임시 prometheus.yml 추가
>
=> [FEAT] Prometheus 설정 추가

com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/controller/ProductController.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/dto/ProductRequestDto.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/dto/ProductResponseDto.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/model/Product.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/service/ProductService.java, com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/type/ApiResultError.java
#71 
- Order애플리케이션에서 주문 성공시 호출할 상품 수량 감소 API 구현
- Order애플리케이션에서 주문 실패시 호출할 상품 수량 증가 API 구현
- 수량이 0이하일 경우 예외발생
>
=> [FEAT] 상품 수량 증가, 감소 기능 구현

com.sparta.logistics.client.hub/build.gradle, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/dto/ProductResponseDto.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/service/ProductService.java, com.sparta.logistics.client.hub/src/main/resources/application.yml, com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/model/EventSerializer.java, docker/docker-compose.yml
#73 
- Product Kafka 추가 (상품 삭제 이벤트 발행)
- 상품 삭제시 상품삭제 이벤트 발행
- 테스트용 이벤트 컨슈머
- 상품 삭제시 구독한 이벤트 처리 (로그)
>
=> [FEAT] Product 상품 Kafka 기능 구현

com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/service/ProductService.java, com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/kafka/ProductDeleted.java
#75 
- 멀티 모듈환경에서 메시지를 받을 수 있도록 공통 모듈에 Dto추가
- 이벤트 발행시 객체생성
- 테스트용 KafkaListener
- KafkaListener 로그
>
=> [FEAT] Product 상품 삭제 Kafka 수정

com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/service/ProductService.java
Issues: #77
#77 
- 주문 취소시 Product 상품 원복 Kafka Listener 스켈레톤 코드 구현
- 주문 취소 이벤트 발행 필요
>
=> [FEAT] 주문 취소시 Product 상품 원복 Kafka Listener

config/prometheus.yml, docker/docker-compose.yml
- #79 
- docker-compose 세팅 (DB, Grafana, Prometheus, Zipkin, Kafka, Redis)
- Prometheus.yml에 각 애플리케이션 설정 추가
>
=> [FEAT] docker-compose 세팅

com.sparta.logistics.client.hub/build.gradle, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/controller/HubController.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/service/ProductService.java, com.sparta.logistics.client.order/build.gradle, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/OrderApplication.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/client/HubClient.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/client/dto/HubPathResponseDto.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/client/dto/HubResponseDto.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/client/dto/ProductResponseDto.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/common/config/QuerydslConfig.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/common/type/OrderStatus.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/controller/OrderController.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/dto/OrderProductResponseDto.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/dto/OrderResponseDto.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/model/Order.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/model/OrderProduct.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/repository/OrderRepository.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/repository/OrderRepositoryCustom.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/repository/OrderRepositoryCustomImpl.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/service/DeliveryPathService.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/service/OrderProcService.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/service/OrderProductService.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/service/OrderService.java, com.sparta.logistics.client.order/src/main/resources/application.yml, com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/model/ApiResult.java, com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/type/ApiResultError.java, docker/docker-compose.yml
Issues : 83
> #83
> 이번 PR에서 진행한 작업을 간략히 설명해주세요. (구체적인 변경사항이나 개선점도 포함)
- Kafka 적용
- order create 시 허브, 제품 정보 검증 추가
- order 사용자 삭제, 자동 삭제 분리
>
=> FEAT : Order create/delete 수정, kafka 적용

com.sparta.logistics.client.gateway/src/main/java/com/sparta/logistics/client/gateway/config/SecurityConfig.java, com.sparta.logistics.client.gateway/src/main/resources/application.yml, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/UserApplication.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/controller/DeliveryManagerController.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/controller/MessageController.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/controller/UserController.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/dto/ManagerRequestDto.java, com.sparta.logistics.common/build.gradle, com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/config/AuditConfig.java, com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/config/AuditorAwareImpl.java, com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/config/JwtTokenProvider.java, com.sparta.logistics.common/src/main/resources/application.yml
issues: #89 #92 
[FEAT] User-Service에서 Security 제거 #89
[FEAT] AuditorAware CommonSetting #92
=> [FEAT] User-Service에서 Security 제거 #89, [FEAT] AuditorAware CommonSetting #92

com.sparta.logistics.client.ai/build.gradle, com.sparta.logistics.client.ai/src/main/java/com/sparta/logistics/client/ai/AiApplication.java, com.sparta.logistics.client.ai/src/main/java/com/sparta/logistics/client/ai/common/config/AppConfig.java, com.sparta.logistics.client.ai/src/main/java/com/sparta/logistics/client/ai/common/config/QueryDSLConfig.java, com.sparta.logistics.client.ai/src/main/java/com/sparta/logistics/client/ai/common/exception/AIException.java, com.sparta.logistics.client.ai/src/main/java/com/sparta/logistics/client/ai/controller/AiController.java, com.sparta.logistics.client.ai/src/main/java/com/sparta/logistics/client/ai/dto/AIApiResponseDto.java, com.sparta.logistics.client.ai/src/main/java/com/sparta/logistics/client/ai/dto/AIRequestDto.java, com.sparta.logistics.client.ai/src/main/java/com/sparta/logistics/client/ai/dto/AIResponseDto.java, com.sparta.logistics.client.ai/src/main/java/com/sparta/logistics/client/ai/dto/AISearchCriteria.java, com.sparta.logistics.client.ai/src/main/java/com/sparta/logistics/client/ai/model/AI.java, com.sparta.logistics.client.ai/src/main/java/com/sparta/logistics/client/ai/model/validation/AIValid0001.java, com.sparta.logistics.client.ai/src/main/java/com/sparta/logistics/client/ai/repository/AIRepository.java, com.sparta.logistics.client.ai/src/main/java/com/sparta/logistics/client/ai/repository/AIRepositoryCustom.java, com.sparta.logistics.client.ai/src/main/java/com/sparta/logistics/client/ai/repository/AIRepositoryCustomImpl.java, com.sparta.logistics.client.ai/src/main/java/com/sparta/logistics/client/ai/service/AIService.java, com.sparta.logistics.client.ai/src/main/resources/application.yml, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/common/config/QueryDSLConfig.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/repository/OrderRepositoryCustomImpl.java, com.sparta.logistics.client.order/src/main/resources/application.yml, com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/type/ApiResultError.java
Issues : 95
> #95 
> AI CRUD 구현
>
=> FEAT : AI CRUD 구현

com.sparta.logistics.client.ai/src/main/java/com/sparta/logistics/client/ai/model/AI.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/client/AiClient.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/client/dto/AiRequestDto.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/controller/HubPathController.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/service/HubPathService.java
#97 
- HubPath 허브 이동 경로 최적의 경로 AI요청 
- AI Entity @Lob어노테이션 추가
>
=> [FEAT] HubPath 허브 이동 경로 AI 기능 구현

com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/client/UserClient.java, com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/model/UserVO.java
>
> ex) #이슈번호, #이슈번호
> 이번 PR에서 진행한 작업을 간략히 설명해주세요. (구체적인 변경사항이나 개선점도 포함)
>
=> [FEAT] common UserClient 생성

com.sparta.logistics.client.gateway/src/main/resources/application.yml, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/HubApplication.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/OrderApplication.java, com.sparta.logistics.client.order/src/main/resources/application.yml, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/service/DeliveryManagerService.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/service/MessageService.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/service/UserService.java
issues: #100 
Hub, Order Swagger 설정
=> [FEAT] 각 서비스 Swagger 설정 #100

com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/HubApplication.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/controller/HubController.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/dto/HubRequestDto.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/model/Hub.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/service/HubService.java
#103 
- Hub 허브 권한 관리 기능 구현
- RoleCheck 어노테이션 적용
- 허브 관리자 (managerUsername) 필드 추가
>
=> [FEAT] Hub 허브 권한 관리 기능 구현

com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/controller/HubPathController.java
Issues: #105
#105 
- RoleCheck 어노테이션 추가
- 허브 이동 경로 생성,수정,삭제는 마스터 관리자만 가능
- 검색 및 조회는 모든 로그인 사용자 가능
>
=> [Feat] HubPath 허브 이동 경로 권한 관리 기능 구현

com.sparta.logistics.client.ai/src/main/java/com/sparta/logistics/client/ai/AiApplication.java, com.sparta.logistics.client.ai/src/main/resources/application.yml, com.sparta.logistics.client.gateway/src/main/resources/application.yml, com.sparta.logistics.client.order/src/main/resources/application.yml, com.sparta.logistics.client.user/src/main/resources/application.yml
issues : #99 
Swagger, Prometheus yml #99
]
=> [FEAT] Swagger, Prometheus yml #99

com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/controller/CompanyController.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/controller/HubController.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/dto/CompanyRequestDto.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/model/Company.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/service/CompanyService.java, com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/type/ApiResultError.java
#108 
- 업체 담당자(companyManagerUsername) 필드 추가
- 업체 ErrorCode 추가
- 마스터: 모든 권한
- 허브 관리자: 자신의 허브에 소속된 업체만 관리 가능
- 허브 업체: 자신의 업체만 수정 가능, 다른 업체의 읽기와 검색만 가능
>
=> [FEAT] Company 업체 권한 관리 기능 구현

com.sparta.logistics.client.auth/src/main/java/com/sparta/logistics/client/auth/infrastructure/configuration/AuthConfig.java, com.sparta.logistics.client.auth/src/main/resources/application.yml, com.sparta.logistics.client.gateway/src/main/resources/application.yml
issues: #99 
[FEAT] Auth 게이트웨이 스웨거 통합 #99
=> [FEAT] Auth 게이트웨이 스웨거 통합 #99

com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/controller/DeliveryManagerController.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/controller/MessageController.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/controller/UserController.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/dto/DeliveryManagerResponseDto.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/dto/MessageResponseDto.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/dto/SearchRequestDto.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/dto/UpdateUserRequestDto.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/dto/UserRequestDto.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/model/User.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/model/validation/UserValid0002.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/repository/UserRepository.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/service/UserService.java
issues : #111 
[FEAT] 회원정보 수정, 삭제된것은 조회X, Dto명 통일
=> [FEAT] 회원정보 수정, 삭제된것은 조회X, Dto명 통일

com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/controller/DeliveryManagerController.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/controller/MessageController.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/dto/ManagerRequestDto.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/dto/MessageRequestDto.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/dto/SearchRequestDto.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/dto/UpdateUserRequestDto.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/dto/UserRequestDto.java
issues : #111 
User-Service Swagger description 추가
=> [FEAT] User-Service Swagger description #111

com.sparta.logistics.client.gateway/src/main/resources/application.yml, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/controller/CompanyController.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/controller/HubController.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/controller/HubPathController.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/controller/ProductController.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/model/Company.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/model/Hub.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/model/HubPath.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/model/Product.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/service/CompanyService.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/service/HubPathService.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/service/HubService.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/service/ProductService.java, com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/model/Timestamped.java, com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/type/ApiResultError.java
#115 
- Product 상품 권한 관리 기능 구현
- softDelete 추가
>
=> [FEAT] Product 상품 권한 관리 기능 구현

com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/controller/HubController.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/client/HubClient.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/dto/HubResponseDto.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/service/DeliveryManagerService.java
issues : #111 
HubClient로 불러온 데이터 Delivery_manager에 넣기
=> [FEAT] HubClient로 불러온 데이터 Delivery_manager에 넣기 #111

com.sparta.logistics.client.auth/build.gradle, com.sparta.logistics.client.auth/src/main/java/com/sparta/logistics/client/auth/application/service/RedisService.java, com.sparta.logistics.client.auth/src/main/java/com/sparta/logistics/client/auth/infrastructure/configuration/RedisConfig.java, com.sparta.logistics.client.auth/src/main/java/com/sparta/logistics/client/auth/presentation/controller/AuthController.java, com.sparta.logistics.client.auth/src/main/resources/application.yml, com.sparta.logistics.client.gateway/build.gradle, com.sparta.logistics.client.gateway/src/main/java/com/sparta/logistics/client/gateway/config/RedisConfig.java, com.sparta.logistics.client.gateway/src/main/java/com/sparta/logistics/client/gateway/config/SecurityConfig.java, com.sparta.logistics.client.gateway/src/main/java/com/sparta/logistics/client/gateway/service/RedisService.java, com.sparta.logistics.client.gateway/src/main/resources/application.yml, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/controller/UserController.java
issues : #121 
인증, 인가에 Redis 추가
=> [FEAT]인증, 인가에 Redis 추가 #121

com.sparta.logistics.common/build.gradle
Issues: #123
#123 
- Zipkin 분산추적에서 다른 서비스 호출할때 트레이스를 하나로 연결
>
=> [FEAT] Zipkin 의존성 추가

com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/controller/DeliveryManagerController.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/controller/UserController.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/dto/UpdateManagerDto.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/model/DeliveryManager.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/repository/DeliveryManagerRepository.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/repository/UserRepository.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/service/DeliveryManagerService.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/service/UserService.java
issues : #111 
delete부분 수정 및 최종 수정
=> [FEAT] delete부분 수정 및 최종 수정#111

com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/controller/HubPathController.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/dto/HubPathRequestDto.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/repository/HubPathRepositoryImpl.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/service/HubPathService.java
Issues: #127
#127 
- 코드 리팩토링
-  HubPath 허브 경로 검색 수정
>
=> [BUG] 코드 리팩토링, HubPath 허브 경로 검색 수정

com.sparta.logistics.client.ai/src/main/java/com/sparta/logistics/client/ai/controller/AIController.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/controller/OrderController.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/dto/DeliveryPathResponseDto.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/dto/OrderAIResponseDto.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/repository/OrderRepositoryCustomImpl.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/service/OrderProcService.java, com.sparta.logistics.client.user/src/main/java/com/sparta/logistics/client/user/Test.java, com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/client/AIClient.java, com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/client/dto/AIRequestDto.java, com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/client/dto/AIResponseDto.java, com.sparta.logistics.common/src/main/java/com/sparta/logistics/common/type/AICallService.java
Issues : 132
> #132 
> order ai 연동
>
=> FEAT : order ai 연동

com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/client/OrderClient.java, com.sparta.logistics.client.hub/src/main/java/com/sparta/logistics/client/hub/service/ProductService.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/controller/OrderController.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/model/Delivery.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/model/DeliveryPath.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/model/Order.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/model/OrderProduct.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/repository/DeliveryRepository.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/service/DeliveryService.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/service/OrderProcService.java
Issues : 136
> #136
> Kafka 재적용
>
=> FEAT : Order kafka 재적용

com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/common/exception/OrderProcException.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/controller/OrderController.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/dto/OrderRequestDto.java, com.sparta.logistics.client.order/src/main/java/com/sparta/logistics/client/order/service/OrderProcService.java
Issues : 138
> #138
> order 수정
>
=> FEAT : Order 수정
